### ISSUE TITLE
Upgrade n5-hdf5 dependency from 1.3.0 to 1.4.2

### ISSUE THREAD

**Issue by mkitti** [saalfeldlab/n5-viewer#25]
We recently released n5-hdf5 1.4.2 after https://github.com/saalfeldlab/n5-hdf5/pull/20 . We may need to do some integration testing here to upgrade n5-hdf5 here from 1.3.0 to 1.4.2.

cc: @bogovicj @cmhulbert

**Comment by bogovicj** [comment]
this has been done for awhile.
