### ISSUE TITLE
File opening dialog throws exception

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/n5-viewer#3]
In a freshly built viewer, selecting a file with the browse button does not open a file dialog but throws an exception.  Entering the location as a file: URL works.

**Comment by igorpisarev** [comment]
Thanks for spotting this! The error occurs when selection history is empty, and was introduced with the recent changes.
Fixed in https://github.com/saalfeldlab/n5-viewer/commit/c30efad91104a6f6efd3e371b7b635009eb58d31
